sonar.projectKey=leszmonitor_leszmonitor
sonar.organization=leszmonitor
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./backend/src,./frontend/src
sonar.go.coverage.reportPaths=backend/src/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=**/*_test.go,**/*.gen.ts,**/routeTree.gen.ts,**/components/ui/*.tsx,**/*.test.tsx,**/*.test.ts
sonar.exclusions=**/*.gen.ts,**/routeTree.gen.ts,**/components/ui/*.tsx
