version: '3'

interval: 1s

vars:
  APP_NAME: 'leszmonitor'
  BIN_DIR: '{{.TASKFILE_DIR}}/bin'  # Absolute path using Task's variable

tasks:
  build:
    desc: Build the backend binary
    alias: b
    cmds:
      - echo "Building {{.APP_NAME}}..."
      - mkdir -p {{.BIN_DIR}}
      - go build -o "{{.BIN_DIR}}/{{.APP_NAME}}" main.go
      - echo "Build complete. Binary at {{.BIN_DIR}}/{{.APP_NAME}}."
    sources:
      - '**/*.go'
    generates:
      - '{{.BIN_DIR}}/{{.APP_NAME}}'

  run:
    - "{{.BIN_DIR}}/{{.APP_NAME}}"

  air:
    desc: Run the backend with air
    alias: a
    cmds:
      - air