version: '3'

vars:
  APP_NAME: 'leszmonitor'
  SERVER_SRC_DIR: '{{.TASKFILE_DIR}}/src'
  SERVER_BIN_DIR: '{{.TASKFILE_DIR}}/bin'
  SQLITE_DB_PATH: '{{.SERVER_SRC_DIR}}/leszmonitor.db'
  DUMP_FILE_PATH: '{{.TASKFILE_DIR}}/db_dump.sql'

env:
  LOG_LEVEL: 'TRACE'
  INSTANCE_ADMIN_USERNAME: 'admin'
  INSTANCE_ADMIN_PASSWORD: '123123'
  SQLITE_DB_PATH: '{{.SQLITE_DB_PATH}}'

tasks:
  build:
    desc: Build the back-end binary
    cmds:
      - echo "Building {{.APP_NAME}}..."
      - mkdir -p {{.SERVER_BIN_DIR}}
      - cd src && go build -v -o "{{.SERVER_BIN_DIR}}/{{.APP_NAME}}" main.go
      - echo "Build complete. Binary at {{.SERVER_BIN_DIR}}/{{.APP_NAME}}."
    sources:
      - '**/*.go'
    generates:
      - '{{.SERVER_BIN_DIR}}/{{.APP_NAME}}'

  run:
    desc: Run the server binary
    env:
      API_PORT: '7001'
      JWT_SECRET: 'your_jwt_secret'
      JWT_EXPIRY_HOURS: '24'
    cmds:
      - "{{.SERVER_BIN_DIR}}/{{.APP_NAME}}"

  dev:
    desc: Run the back-end dev server with air for live reload
    env:
      API_PORT: '7001'
      JWT_SECRET: 'your_jwt_secret'
      JWT_EXPIRY_HOURS: '24'
    cmds:
      - cd {{.SERVER_SRC_DIR}} && $(go env GOPATH)/bin/air -build.stop_on_error true

  docker:run:
    desc: Run the Docker image
    env:
      API_PORT: '7001'
      JWT_SECRET: 'your_jwt_secret'
      JWT_EXPIRY_HOURS: '24'
    cmds:
      - "{{.SERVER_BIN_DIR}}/{{.APP_NAME}}"

  clean:
    desc: Clean the back-end build artifacts
    cmds:
      - rm -r {{.SERVER_BIN_DIR}}/{{.APP_NAME}} || true

  test:
    desc: Run the back-end tests
    dir: src
    cmds:
      - go run gotest.tools/gotestsum@latest --format testdox ./...

  coverage:
    desc: Run the back-end tests with coverage
    dir: src
    cmds:
      - go test -coverpkg=./... -coverprofile=coverage.out -v ./...
    generates:
      - 'coverage.out'

  db:dump:
    desc: Dump the SQLite database to a file
    dir: src
    cmds:
      - sqlite3 {{.SQLITE_DB_PATH}} .dump > {{.DUMP_FILE_PATH}}
    generates:
      - '{{.DUMP_FILE_PATH}}'

  db:restore:
    desc: Restore the SQLite database from a dump file
    dir: src
    cmds:
      - sqlite3 {{.SQLITE_DB_PATH}} < {{.DUMP_FILE_PATH}}