/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAuditLogIndexRouteImport } from './routes/_authenticated/audit-log/index'
import { Route as AuthenticatedDocsIndexRouteImport } from './routes/_authenticated/docs/index'
import { Route as AuthenticatedMonitorsIndexRouteImport } from './routes/_authenticated/monitors/index'
import { Route as AuthenticatedMonitorsMonitorSlugIndexRouteImport } from './routes/_authenticated/monitors/$monitorSlug/index'
import { Route as AuthenticatedMonitorsMonitorSlugEditRouteImport } from './routes/_authenticated/monitors/$monitorSlug/edit'
import { Route as AuthenticatedMonitorsNewIndexRouteImport } from './routes/_authenticated/monitors/new/index'
import { Route as AuthenticatedUserUsernameIndexRouteImport } from './routes/_authenticated/user/$username/index'
import { Route as AuthenticatedUserUsernameSettingsIndexRouteImport } from './routes/_authenticated/user/$username/settings/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogIndexRoute =
  AuthenticatedAuditLogIndexRouteImport.update({
    id: '/audit-log/',
    path: '/audit-log/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocsIndexRoute = AuthenticatedDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitorsIndexRoute =
  AuthenticatedMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsMonitorSlugIndexRoute =
  AuthenticatedMonitorsMonitorSlugIndexRouteImport.update({
    id: '/monitors/$monitorSlug/',
    path: '/monitors/$monitorSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsMonitorSlugEditRoute =
  AuthenticatedMonitorsMonitorSlugEditRouteImport.update({
    id: '/monitors/$monitorSlug/edit',
    path: '/monitors/$monitorSlug/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsNewIndexRoute =
  AuthenticatedMonitorsNewIndexRouteImport.update({
    id: '/monitors/new/',
    path: '/monitors/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserUsernameIndexRoute =
  AuthenticatedUserUsernameIndexRouteImport.update({
    id: '/user/$username/',
    path: '/user/$username/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserUsernameSettingsIndexRoute =
  AuthenticatedUserUsernameSettingsIndexRouteImport.update({
    id: '/user/$username/settings/',
    path: '/user/$username/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/audit-log/': typeof AuthenticatedAuditLogIndexRoute
  '/docs/': typeof AuthenticatedDocsIndexRoute
  '/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/monitors/$monitorSlug/edit': typeof AuthenticatedMonitorsMonitorSlugEditRoute
  '/monitors/$monitorSlug/': typeof AuthenticatedMonitorsMonitorSlugIndexRoute
  '/monitors/new/': typeof AuthenticatedMonitorsNewIndexRoute
  '/user/$username/': typeof AuthenticatedUserUsernameIndexRoute
  '/user/$username/settings/': typeof AuthenticatedUserUsernameSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/audit-log': typeof AuthenticatedAuditLogIndexRoute
  '/docs': typeof AuthenticatedDocsIndexRoute
  '/monitors': typeof AuthenticatedMonitorsIndexRoute
  '/monitors/$monitorSlug/edit': typeof AuthenticatedMonitorsMonitorSlugEditRoute
  '/monitors/$monitorSlug': typeof AuthenticatedMonitorsMonitorSlugIndexRoute
  '/monitors/new': typeof AuthenticatedMonitorsNewIndexRoute
  '/user/$username': typeof AuthenticatedUserUsernameIndexRoute
  '/user/$username/settings': typeof AuthenticatedUserUsernameSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/audit-log/': typeof AuthenticatedAuditLogIndexRoute
  '/_authenticated/docs/': typeof AuthenticatedDocsIndexRoute
  '/_authenticated/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/_authenticated/monitors/$monitorSlug/edit': typeof AuthenticatedMonitorsMonitorSlugEditRoute
  '/_authenticated/monitors/$monitorSlug/': typeof AuthenticatedMonitorsMonitorSlugIndexRoute
  '/_authenticated/monitors/new/': typeof AuthenticatedMonitorsNewIndexRoute
  '/_authenticated/user/$username/': typeof AuthenticatedUserUsernameIndexRoute
  '/_authenticated/user/$username/settings/': typeof AuthenticatedUserUsernameSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/register/'
    | '/admin/'
    | '/audit-log/'
    | '/docs/'
    | '/monitors/'
    | '/monitors/$monitorSlug/edit'
    | '/monitors/$monitorSlug/'
    | '/monitors/new/'
    | '/user/$username/'
    | '/user/$username/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/audit-log'
    | '/docs'
    | '/monitors'
    | '/monitors/$monitorSlug/edit'
    | '/monitors/$monitorSlug'
    | '/monitors/new'
    | '/user/$username'
    | '/user/$username/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/login/'
    | '/register/'
    | '/_authenticated/admin/'
    | '/_authenticated/audit-log/'
    | '/_authenticated/docs/'
    | '/_authenticated/monitors/'
    | '/_authenticated/monitors/$monitorSlug/edit'
    | '/_authenticated/monitors/$monitorSlug/'
    | '/_authenticated/monitors/new/'
    | '/_authenticated/user/$username/'
    | '/_authenticated/user/$username/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log/': {
      id: '/_authenticated/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuthenticatedAuditLogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs/': {
      id: '/_authenticated/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthenticatedDocsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/': {
      id: '/_authenticated/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AuthenticatedMonitorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/$monitorSlug/': {
      id: '/_authenticated/monitors/$monitorSlug/'
      path: '/monitors/$monitorSlug'
      fullPath: '/monitors/$monitorSlug/'
      preLoaderRoute: typeof AuthenticatedMonitorsMonitorSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/$monitorSlug/edit': {
      id: '/_authenticated/monitors/$monitorSlug/edit'
      path: '/monitors/$monitorSlug/edit'
      fullPath: '/monitors/$monitorSlug/edit'
      preLoaderRoute: typeof AuthenticatedMonitorsMonitorSlugEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/new/': {
      id: '/_authenticated/monitors/new/'
      path: '/monitors/new'
      fullPath: '/monitors/new/'
      preLoaderRoute: typeof AuthenticatedMonitorsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$username/': {
      id: '/_authenticated/user/$username/'
      path: '/user/$username'
      fullPath: '/user/$username/'
      preLoaderRoute: typeof AuthenticatedUserUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$username/settings/': {
      id: '/_authenticated/user/$username/settings/'
      path: '/user/$username/settings'
      fullPath: '/user/$username/settings/'
      preLoaderRoute: typeof AuthenticatedUserUsernameSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAuditLogIndexRoute: typeof AuthenticatedAuditLogIndexRoute
  AuthenticatedDocsIndexRoute: typeof AuthenticatedDocsIndexRoute
  AuthenticatedMonitorsIndexRoute: typeof AuthenticatedMonitorsIndexRoute
  AuthenticatedMonitorsMonitorSlugEditRoute: typeof AuthenticatedMonitorsMonitorSlugEditRoute
  AuthenticatedMonitorsMonitorSlugIndexRoute: typeof AuthenticatedMonitorsMonitorSlugIndexRoute
  AuthenticatedMonitorsNewIndexRoute: typeof AuthenticatedMonitorsNewIndexRoute
  AuthenticatedUserUsernameIndexRoute: typeof AuthenticatedUserUsernameIndexRoute
  AuthenticatedUserUsernameSettingsIndexRoute: typeof AuthenticatedUserUsernameSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAuditLogIndexRoute: AuthenticatedAuditLogIndexRoute,
  AuthenticatedDocsIndexRoute: AuthenticatedDocsIndexRoute,
  AuthenticatedMonitorsIndexRoute: AuthenticatedMonitorsIndexRoute,
  AuthenticatedMonitorsMonitorSlugEditRoute:
    AuthenticatedMonitorsMonitorSlugEditRoute,
  AuthenticatedMonitorsMonitorSlugIndexRoute:
    AuthenticatedMonitorsMonitorSlugIndexRoute,
  AuthenticatedMonitorsNewIndexRoute: AuthenticatedMonitorsNewIndexRoute,
  AuthenticatedUserUsernameIndexRoute: AuthenticatedUserUsernameIndexRoute,
  AuthenticatedUserUsernameSettingsIndexRoute:
    AuthenticatedUserUsernameSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
