/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedDocsIndexRouteImport } from './routes/_authenticated/docs/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedUserUsernameIndexRouteImport } from './routes/_authenticated/user/$username/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedUserUsernameSettingsIndexRouteImport } from './routes/_authenticated/user/$username/settings/index'
import { Route as AuthenticatedProjectsProjectIdMonitorsIndexRouteImport } from './routes/_authenticated/projects/$projectId/monitors/index'
import { Route as AuthenticatedProjectsProjectIdMembersIndexRouteImport } from './routes/_authenticated/projects/$projectId/members/index'
import { Route as AuthenticatedProjectsProjectIdMonitorsNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/monitors/new/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocsIndexRoute = AuthenticatedDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserUsernameIndexRoute =
  AuthenticatedUserUsernameIndexRouteImport.update({
    id: '/user/$username/',
    path: '/user/$username/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedUserUsernameSettingsIndexRoute =
  AuthenticatedUserUsernameSettingsIndexRouteImport.update({
    id: '/user/$username/settings/',
    path: '/user/$username/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdMonitorsIndexRoute =
  AuthenticatedProjectsProjectIdMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersIndexRoute =
  AuthenticatedProjectsProjectIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMonitorsNewIndexRoute =
  AuthenticatedProjectsProjectIdMonitorsNewIndexRouteImport.update({
    id: '/monitors/new/',
    path: '/monitors/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/docs/': typeof AuthenticatedDocsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/user/$username/': typeof AuthenticatedUserUsernameIndexRoute
  '/projects/$projectId/members/': typeof AuthenticatedProjectsProjectIdMembersIndexRoute
  '/projects/$projectId/monitors/': typeof AuthenticatedProjectsProjectIdMonitorsIndexRoute
  '/user/$username/settings/': typeof AuthenticatedUserUsernameSettingsIndexRoute
  '/projects/$projectId/monitors/new/': typeof AuthenticatedProjectsProjectIdMonitorsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/docs': typeof AuthenticatedDocsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/user/$username': typeof AuthenticatedUserUsernameIndexRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersIndexRoute
  '/projects/$projectId/monitors': typeof AuthenticatedProjectsProjectIdMonitorsIndexRoute
  '/user/$username/settings': typeof AuthenticatedUserUsernameSettingsIndexRoute
  '/projects/$projectId/monitors/new': typeof AuthenticatedProjectsProjectIdMonitorsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/docs/': typeof AuthenticatedDocsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/user/$username/': typeof AuthenticatedUserUsernameIndexRoute
  '/_authenticated/projects/$projectId/members/': typeof AuthenticatedProjectsProjectIdMembersIndexRoute
  '/_authenticated/projects/$projectId/monitors/': typeof AuthenticatedProjectsProjectIdMonitorsIndexRoute
  '/_authenticated/user/$username/settings/': typeof AuthenticatedUserUsernameSettingsIndexRoute
  '/_authenticated/projects/$projectId/monitors/new/': typeof AuthenticatedProjectsProjectIdMonitorsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/register/'
    | '/projects/$projectId'
    | '/docs/'
    | '/projects/'
    | '/projects/$projectId/'
    | '/user/$username/'
    | '/projects/$projectId/members/'
    | '/projects/$projectId/monitors/'
    | '/user/$username/settings/'
    | '/projects/$projectId/monitors/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/docs'
    | '/projects'
    | '/projects/$projectId'
    | '/user/$username'
    | '/projects/$projectId/members'
    | '/projects/$projectId/monitors'
    | '/user/$username/settings'
    | '/projects/$projectId/monitors/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/login/'
    | '/register/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/docs/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/user/$username/'
    | '/_authenticated/projects/$projectId/members/'
    | '/_authenticated/projects/$projectId/monitors/'
    | '/_authenticated/user/$username/settings/'
    | '/_authenticated/projects/$projectId/monitors/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs/': {
      id: '/_authenticated/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthenticatedDocsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$username/': {
      id: '/_authenticated/user/$username/'
      path: '/user/$username'
      fullPath: '/user/$username/'
      preLoaderRoute: typeof AuthenticatedUserUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/user/$username/settings/': {
      id: '/_authenticated/user/$username/settings/'
      path: '/user/$username/settings'
      fullPath: '/user/$username/settings/'
      preLoaderRoute: typeof AuthenticatedUserUsernameSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/monitors/': {
      id: '/_authenticated/projects/$projectId/monitors/'
      path: '/monitors'
      fullPath: '/projects/$projectId/monitors/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMonitorsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/members/': {
      id: '/_authenticated/projects/$projectId/members/'
      path: '/members'
      fullPath: '/projects/$projectId/members/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/monitors/new/': {
      id: '/_authenticated/projects/$projectId/monitors/new/'
      path: '/monitors/new'
      fullPath: '/projects/$projectId/monitors/new/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMonitorsNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdMembersIndexRoute: typeof AuthenticatedProjectsProjectIdMembersIndexRoute
  AuthenticatedProjectsProjectIdMonitorsIndexRoute: typeof AuthenticatedProjectsProjectIdMonitorsIndexRoute
  AuthenticatedProjectsProjectIdMonitorsNewIndexRoute: typeof AuthenticatedProjectsProjectIdMonitorsNewIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdMembersIndexRoute:
      AuthenticatedProjectsProjectIdMembersIndexRoute,
    AuthenticatedProjectsProjectIdMonitorsIndexRoute:
      AuthenticatedProjectsProjectIdMonitorsIndexRoute,
    AuthenticatedProjectsProjectIdMonitorsNewIndexRoute:
      AuthenticatedProjectsProjectIdMonitorsNewIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedDocsIndexRoute: typeof AuthenticatedDocsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedUserUsernameIndexRoute: typeof AuthenticatedUserUsernameIndexRoute
  AuthenticatedUserUsernameSettingsIndexRoute: typeof AuthenticatedUserUsernameSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedDocsIndexRoute: AuthenticatedDocsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedUserUsernameIndexRoute: AuthenticatedUserUsernameIndexRoute,
  AuthenticatedUserUsernameSettingsIndexRoute:
    AuthenticatedUserUsernameSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
