version: 3

tasks:
  test:
    desc: Run end-to-end tests
    cmds:
      - npx playwright test

  test:headed:
    desc: Run end-to-end tests in headed mode
    cmds:
      - npx playwright test --headed

  test:ui:
    desc: Run end-to-end tests in headed mode
    cmds:
      - npx playwright test --ui