name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  backend:
    name: Back-end
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'
          cache: true
          cache-dependency-path: backend/src/go.sum

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Mock frontend assets
        run: |
          mkdir -p backend/src/static &&
          touch backend/src/static/index.html

      - name: Build Backend
        run: task backend:build

      - name: Test Backend
        run: task backend:coverage

      - name: Upload Go Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: go-coverage-report
          path: backend/src/coverage.out
          retention-days: 1

  frontend:
    name: Front-end
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test:coverage

      - name: Upload TS Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: ts-coverage-report
          path: frontend/coverage
          retention-days: 1

      - name: Build application
        run: npm run build

  sonar:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download Go Coverage Report
        uses: actions/download-artifact@v6
        with:
          name: go-coverage-report
          path: backend/src

      - name: Download TS Coverage Report
        uses: actions/download-artifact@v6
        with:
          name: ts-coverage-report
          path: frontend/coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Exit with status 0 to prevent failure
        if: always()
        run: exit 0
