name: Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build the app image
        run: |
          task docker:build
